tap "caskroom/cask"
tap "caskroom/versions"
tap "homebrew/binary"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/services"
tap "homebrew/versions"
tap "sanemat/font"
cask "java"
brew "git"
brew "carthage"
brew "curl"
brew "direnv"
brew "elasticsearch"
brew "ffmpeg"
brew "gawk"
brew "gcc"
brew "go"
brew "hub"
brew "imagemagick"
brew "jq"
brew "mitmproxy"
brew "mysql@5.6", restart_service: true
brew "peco"
brew "postgresql", restart_service: true
brew "qt"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "tig"
brew "tmux"
brew "tree"
brew "yarn"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "sanemat/font/ricty", args: ["with-powerline"]
cask "alfred"
cask "bettertouchtool"
cask "google-japanese-ime"
cask "hosts"
cask "imageoptim"
cask "iterm2"
cask "karabiner-elements"
cask "sequel-pro"
cask "skitch"
cask "the-unarchiver"
cask "tower"
