tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "sanemat/font"
brew "curl"
brew "direnv"
brew "elasticsearch"
brew "fzf"
brew "gcc"
brew "ghq"
brew "git"
brew "hub"
brew "imagemagick@6"
brew "jq"
brew "mysql", restart_service: true
brew "mysql@5.6", restart_service: true
brew "neovim"
brew "peco"
brew "postgresql", restart_service: true
brew "pwgen"
brew "qt"
brew "redis", restart_service: true
brew "tig"
brew "tmux"
brew "tree"
brew "yarn"
brew "zsh"
brew "sanemat/font/ricty", args: ["with-powerline"]
cask "alfred"
cask "atom"
cask "bettertouchtool"
cask "docker"
cask "google-japanese-ime"
cask "iterm2"
cask "java"
cask "java8"
cask "karabiner-elements"
cask "rubymine"
cask "sequel-pro"
cask "skitch"
cask "slack"
